spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?createDatabaseIfNotExist=true
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true